### ISSUE TITLE
Does cosmo support event sharing

### ISSUE THREAD

**Issue by devbikash** [1and1/cosmo#13]
can i add invitee to a event in cosmo. also is there a client i can use cosmo with...i tried Evolution but it does not connect

**Comment by danielgrigore** [comment]
You can add invitee to events as long as you use the CalDAV protocol. I did not try Evolution but it works with Lightning plugin for Thunderbird.
Cheers,

**Comment by achrefath** [comment]
hello, am using Lightning with Thunderbird , i create an event and add invitee without problem. but the  notification mail to the attendee does not work for me!

**Comment by danielgrigore** [comment]
Hi achrefath,

Sending emails for invitations would involve complex logic like what smtp server to use, what templates to use, etc. That's why this is designed as an extension. You can achieve this by implementing interceptors in your web applications. You can have a look at `cosmo-api/src/main/java/org/unitedinternet/cosmo/service/interceptors/EventAddHandler.java` and also at the demo web application. You can find there some examples of interceptors.
Cheers,

**Comment by AnisGitRepo** [comment]
Hello, am using a cosmo caldav server and i want to add synchronization feature in order to import events from all my application users gmail account. Did you guys have an idea about to do it with cosmo

**Comment by f1-outsourcing** [comment]
> You can add invitee to events as long as you use the CalDAV protocol. I did not try Evolution but it works with Lightning plugin for Thunderbird. Cheers,

I have currently two calendars accounts in Thunderbird. If I create an event  in one calendar and add invite the 2nd account, should I then see this event automatically in the the 2nd calendar?
Currently nothing seems to happen or should I configure the demo application in some way to get this to work?
