### ISSUE TITLE
Owner is set as the user when I create a ticket.

### ISSUE THREAD

**Issue by tomschilling** [1and1/cosmo#17]
Hello all. I wanted to create a ticket for another user. But I found in the sources that always the user is set as the owner. Shouldn't the owner be the user the ticket was given to?

Otherwise a ticket cannot be assigned to a specific person?

Here you find the used XML request:

```
<?xml version="1.0" encoding="UTF-8"?>
<X:ticketinfo xmlns:D="DAV:" 
              xmlns:X="http://www.xythos.com/namespaces/StorageServer">
<D:privilege>
  <D:read/>
  <D:write/>
</D:privilege>
<D:owner>
  <D:href>:SERVER/cosmo/dav/users/:USER</D:href>
</D:owner>
</X:ticketinfo>
```

As well as  the snipped  from the sources:

https://github.com/1and1/cosmo/blob/61d14f4912655ee8946e962aa7707e83eee1f936/cosmo-core/src/main/java/org/unitedinternet/cosmo/dav/provider/BaseProvider.java#L318

Shouldn't be this the assigned owner from xml request?

**Comment by danielgrigore** [comment]
Hi Tom,
The owner of the ticket is the one that creates it and this is the way it goes for a couple of reasons.
One use case where tickets are created is when an event organizer sends invitations to a couple of attendees. The organizer will create tickets for each attendee so that they can reply with a response (Accept/Tentative/Deny). The attendees don't even need to be users of the same system with the organizer. They just need to have an email address where to receive an URL with the ticket that gives them the right to reply.
Organizer may also remove an attendee from an event and in this case he/she needs to have the possibility to revoke/delete the ticket for that specific attendee.

Cheers,

**Comment by tomschilling** [comment]
Hey Daniel,
thanks for your quick response. 

Okay I get that use case. It's great, that attendees don't even have to be users of the same system!

But how do you know which ticket belongs to which attendee? 

I couldn't find any information on the ticket:

<img width="127" alt="screenshot 2018-12-13 at 16 08 55" src="https://user-images.githubusercontent.com/19814840/49948245-616f6b00-fef3-11e8-8a8a-7b4984b94c9b.png">

And sorry, I actually have one more question to ask. How does it work to share calendars with other users in the system? Is this also a use case where tickets are created?

**Comment by danielgrigore** [comment]
Hi Tom,

Related to your first question: Cosmo is only a CalDAV server and contains the minimum necessary for this. You will need to add your own logic related to tickets, attendees and email sending for instance. You could add an extra table for example to keep track of attendees and tickets.

Related to the second question: Sharing calendars with other users is a another use case which involves creating tickets. Please have a look at  `HibCollectionSubscription` and `HibernateCollectionSubscriptionDaoTest` classes to get a feeling of how collection subscription is modeled.

Cheers,

**Comment by tomschilling** [comment]
Hey David. 

Thanks, has helped me so much to understand the usage of the tickets.
