### ISSUE TITLE
Switch to an existing DB

### ISSUE THREAD

**Issue by ronaksv** [1and1/cosmo#21]
Hi, 
I setup the project successfully and its running fine. But when I close the application, it deletes the database.
How can I keep a consistent database so that even after closing the server, the data sustains?
Secondly, I want to keep the DB out of the application. 
In this application, it creates a DB inside a target folder and then connects to it.
I want to create a DB outside the application and then it will just connect to that DB.

**Comment by eardeleanu15** [comment]
Hi,
First you'll need to provision a DB outside the application and configure database schema by running the SQL statements from **cosmo-core/src/main/resources/db/cosmo-schema.sql**. Database name and user credentials don't have any conventions since you'll configure them as properties in cosmo-webapp application (see below).

After you finish with your database setup, you'll need to do two more steps:
1.  Update properties spring.datasource.jdbcUrl, spring.datasource.username and spring.datasource.password from  **cosmo-webapp/src/main/resources/application.yaml** according with your database configuration.
2.  Comment/Delete  **mariaDB**  bean definition from DataSourceConfig and also comment/delete 
**@DependsOn("mariaDB")** from **DataSource** bean definition (in the same DataSourceConfig class). Only having 
`@Bean
  public DataSource ds() {
        return new HikariDataSource(this);
    }` should work.

Hope this helps!

**Comment by ronaksv** [comment]
Thanks a lot for this!!
Also for my second question: "How to sustain the data?", I found the option.
In application.yaml change "hibernate.hbm2ddl.auto: create" to "hibernate.hbm2ddl.auto: validate"
