### ISSUE TITLE
is there a configuration option not to have to sign on with an email address

### ISSUE THREAD

**Issue by f1-outsourcing** [1and1/cosmo#47]
I am not sure if this caldav url is forced by standards, but I would like to use normal user accounts. Would this be easy to change?

` curl -X"MKCALENDAR" -H"Content-Type:application/xml" -uusertest:testtest http://localhost:8080/cosmo/dav/usertest/calendar`

rpolatedMessage='not a well-formed email address', propertyPath=email, rootBeanClass=class org.unitedinternet.cosmo.model.hibernate.HibUser, messageTemplate='{org.hibernate.validator.constraints.Email.message}'}

**Comment by danielgrigore** [comment]
Hi @f1-outsourcing ,

Since you need to provide your own `AuthenticationProvider` implementation anyway you can create one that performs the authentication using username and password.
However you still need to provide at least one email address for each user because that email address is needed when creating events to populate the `ORGANIZER` property.
Cheers,

**Comment by f1-outsourcing** [comment]
Is there an example of an openldap AuthenticationProvider available?

**Comment by danielgrigore** [comment]
>Is there an example of an openldap AuthenticationProvider available?

Not in cosmo, but you can search form some Spring/Spring-Boot examples.
