### ISSUE TITLE
Building version 0.99 fails

### ISSUE THREAD

**Issue by manubaum** [1and1/cosmo#5]
When doing as adviced:
"In the project's root directory just run mvn tomcat7:run-war."
..
[INFO] --- tomcat7-maven-plugin:2.2:run-war (default-cli) @ cosmo-core ---
[INFO] Skipping non-war project
..

Nothing happens due to the missing module reference to cosmo-webapp in the root pom. The following line needs to be added in the modules section:
<module>cosmo-webapp</module>

Furthermore the parent pom version in cosmo-webapp is invalid and needs to be:
<version>0.99-SNAPSHOT</version>

Furthermore the reference in cosmo-core to cosmo-webapp is not valid.

**Comment by danielpopa1986** [comment]
Hi manubaum,

We've updated the cosmo-webapp pom according to the new version of the cosmo-core. It should all be  working now.
We've modified the project and took out the cosmo-webapp module from the parent pom because it should be seen like a separate application. 
We will also change the documentation accordingly.

Now if you run a "mvn clean install" on the root pom you should be able after that to successfully run "mvn tomcat7:run-war" in the "cosmo-webapp" folder.

Regards,
Daniel

**Comment by manubaum** [comment]
Yes that works too. Thanks.
