### ISSUE TITLE
only possible to have one users access it's calendar?

### ISSUE THREAD

**Issue by f1-outsourcing** [1and1/cosmo#75]
https://github.com/1and1/cosmo/pull/33

I don't really get this "beyond cosmo's purpose", why would scheduling be not be interesting to add? The same is with this group-membership ( I don't really know what this is, I assume you can grant access to your calendar etc)

I would like to maintain a calendar on the phone/desktop that is being published on a website. Is this even possible with cosmo to have read only access to a specific user calendar?

**Comment by danielgrigore** [comment]
Scheduling implies email sending. 
You want the attendees to accept/tentative/deny the invitations. Implementing an email service has a lot of implications (like SMTP server, templates for messages etc.) 
For this reason it won't be implemented directly in cosmo because the implementation would be too specific.
There's the possibility to extend cosmo by adding `EventHandlers` like the ones in [cosmo demo webapp](https://github.com/1and1/cosmo/blob/master/cosmo-webapp/src/main/java/org/unitedinternet/cosmo/service/interceptors/FirstLoggingEventAddHandler.java). Each implementation could extend cosmo by adding the desired extra behavior.

The sharing scenario above is not possible in cosmo, but again you could extend the application by adding your own http servlet  that serves ICS content of calendar or any other format you may need.

Cheers,

**Comment by f1-outsourcing** [comment]
I am interested in being able to share the calendar with the website (obviously read only). I would appreciate your advice on how to do this best?

**Comment by danielgrigore** [comment]
For your sharing use-case I would go with `Ticket` and `CollectionItem` classes and a custom servlet (as mentioned above) to check the the privileges and serve the content.
